<?php

namespace Database\Seeders;

use App\Models\News;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class NewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear any existing news
        News::query()->delete();

        $newsData = [
            [
                'title_id' => 'Pengumuman Kelompok Capstone Design Project',
                'title_en' => 'Announcement of Capstone Design Project Groups',
                'excerpt_id' => 'Pengumuman kelompok mahasiswa yang diterima pada skema Topik Dosen Program Studi S1 Teknik Logistik.',
                'excerpt_en' => 'Announcement of student groups accepted under the Lecturer Topic scheme for the S1 Logistics Engineering Study Program.',
                'body_id' => "Pengumuman Kelompok Capstone Design Project\n\nDengan ini diumumkan kelompok mahasiswa yang DITERIMA pada skema Topik Dosen Program Studi S1 Teknik Logistik.\nSelamat kepada seluruh mahasiswa yang telah lolos seleksi. Diharapkan seluruh anggota kelompok dapat mengikuti arahan dan ketentuan pelaksanaan Capstone Design Project sesuai dengan topik yang telah ditetapkan",
                'body_en' => "Announcement of Capstone Design Project Groups\n\nWe hereby announce the student groups ACCEPTED under the Lecturer Topic scheme for the S1 Logistics Engineering Study Program.\nCongratulations to all students who passed the selection. It is expected that all group members follow the directions and guidelines for executing the Capstone Design Project in accordance with the assigned topic.",
                'category' => 'pengumuman',
                'featured_image' => '/images/news/pengumuman_kelompok capstone.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(1),
                'views' => 143,
            ],
            [
                'title_id' => 'LOGISTICS TALK Vol. 11: Supply Chain in Society 5.0',
                'title_en' => 'LOGISTICS TALK Vol. 11: Supply Chain in Society 5.0',
                'excerpt_id' => 'Kuliah tamu Logistics Talk Vol. 11 bertema Supply Chain in Society 5.0 bersama pembicara dari Edith Cowan University.',
                'excerpt_en' => 'Guest lecture Logistics Talk Vol. 11 themed Supply Chain in Society 5.0 featuring a speaker from Edith Cowan University.',
                'body_id' => "✨ LOGISTICS TALK Vol. 11 ✨\n“Supply Chain in the Future: Supply Chain in Society 5.0”\n\nGain valuable insights into the future of supply chain management and innovation directly from an international expert speaker, the Lecturer at Edith Cowan University.\n\n🗓 Friday, May 22nd, 2026\n⏰ 01:30 – 03:15 PM\n📍 Auditorium, 16th Floor, Telkom University Landmark Tower\n\nDon’t miss this opportunity to gain valuable insights and broaden your understanding of the future supply chain industry.\nSee you there! ✨",
                'body_en' => "✨ LOGISTICS TALK Vol. 11 ✨\n“Supply Chain in the Future: Supply Chain in Society 5.0”\n\nGain valuable insights into the future of supply chain management and innovation directly from an international expert speaker, the Lecturer at Edith Cowan University.\n\n🗓 Friday, May 22nd, 2026\n⏰ 01:30 – 03:15 PM\n📍 Auditorium, 16th Floor, Telkom University Landmark Tower\n\nDon’t miss this opportunity to gain valuable insights and broaden your understanding of the future supply chain industry.\nSee you there! ✨",
                'category' => 'berita',
                'featured_image' => '/images/news/news_logistictalk.png',
                'is_featured' => true,
                'status' => 'published',
                'published_at' => now()->subDays(2),
                'views' => 218,
            ],
            [
                'title_id' => 'Studium Generale: Peranan Sistem Rekayasa Industri dalam Peningkatan Produktivitas Nasional',
                'title_en' => 'Studium Generale: The Role of Industrial Engineering Systems in Enhancing National Productivity',
                'excerpt_id' => 'Fakultas Rekayasa Industri Telkom University mengundang Anda untuk mengikuti Studium Generale bersama Menteri Ketenagakerjaan RI.',
                'excerpt_en' => 'Faculty of Industrial Engineering Telkom University invites you to join the Studium Generale featuring the Minister of Manpower of the Republic of Indonesia.',
                'body_id' => "Fakultas Rekayasa Industri Telkom University mengundang Anda untuk mengikuti Studium Generale dengan tema:\n\n“Peranan Sistem Rekayasa Industri dalam Peningkatan Produktivitas Nasional”\n\n🎤 Bersama:\nProf. Yassierli, Ph.D.\nMenteri Ketenagakerjaan Republik Indonesia\n\n📅 Jumat, 8 Mei 2026\n🕐 13.00 – 15.00 WIB\n📍 R. Auditorium, Gedung Damar, Telkom University\n\n🔗 Daftar sekarang:\nhttps://bit.ly/studiumgenerale2026\n\nKegiatan ini menghadirkan wawasan strategis tentang bagaimana rekayasa industri berkontribusi dalam peningkatan produktivitas nasional. Jangan lewatkan kesempatan berharga ini!",
                'body_en' => "Faculty of Industrial Engineering Telkom University invites you to join the Studium Generale with the theme:\n\n\"The Role of Industrial Engineering Systems in Enhancing National Productivity\"\n\n🎤 With:\nProf. Yassierli, Ph.D.\nMinister of Manpower of the Republic of Indonesia\n\n📅 Friday, May 8, 2026\n🕐 13.00 – 15.00 WIB\n📍 Auditorium Room, Damar Building, Telkom University\n\n🔗 Register now:\nhttps://bit.ly/studiumgenerale2026\n\nThis event presents strategic insights on how industrial engineering contributes to national productivity. Don't miss this valuable opportunity!",
                'category' => 'berita',
                'featured_image' => '/images/news/news_studiumgenerale.png',
                'is_featured' => true,
                'status' => 'published',
                'published_at' => now()->subDays(3),
                'views' => 312,
                'order' => 2,
            ],
            [
                'title_id' => 'Himpunan Mahasiswa HMTI dan DISCA Lolos Seleksi PPKO Universitas Telkom 2025',
                'title_en' => 'HMTI and DISCA Student Association Pass 2025 PPKO Selection of Telkom University',
                'excerpt_id' => 'Selamat kepada organisasi mahasiswa FRI yang berhasil lolos Program Penguatan Kapasitas Organisasi Mahasiswa (PPKO) 2025.',
                'excerpt_en' => 'Congratulations to FRI student organizations for successfully passing the 2025 Student Organization Capacity Strengthening Program (PPKO).',
                'body_id' => "🎉 Selamat kepada organisasi mahasiswa Fakultas Rekayasa Industri yang telah berhasil lolos seleksi Program Penguatan Kapasitas Organisasi Mahasiswa (PPKO) Universitas Telkom tahun 2025! 🥳👏\n\nBerikut organisasi yang berhasil lolos:\n🔸 Himpunan Mahasiswa Teknik Industri (HMTI)\n🔸 Himpunan Mahasiswa Digital Supply Chain (DISCA)\n\nDedikasi dan semangat untuk terus berkontribusi dalam pengembangan kapasitas mahasiswa telah membuktikan bahwa kita semua mampu memberikan yang terbaik untuk almamater tercinta. 💪\n\nTeruslah berkarya, menginspirasi, dan membawa nama baik Fakultas Rekayasa Industri! 🙌",
                'body_en' => "🎉 Congratulations to the student organizations of the Faculty of Industrial Engineering for passing the selection for the Student Organization Capacity Strengthening Program (PPKO) of Telkom University in 2025! 🥳👏\n\nHere are the selected organizations:\n🔸 Himpunan Mahasiswa Teknik Industri (HMTI)\n🔸 Himpunan Mahasiswa Digital Supply Chain (DISCA)\n\nDedication and enthusiasm to continue contributing to student capacity development prove that we can deliver the best for our beloved almamater. 💪\n\nKeep creating, inspiring, and bringing pride to the Faculty of Industrial Engineering! 🙌",
                'category' => 'prestasi',
                'featured_image' => '/images/news/achievement_PPKO.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(4),
                'views' => 195,
            ],
            [
                'title_id' => 'Tim Younme Lolos Pendanaan Program Pembinaan Mahasiswa Wirausaha (P2MW) 2025',
                'title_en' => 'Younme Team Passes Funding for the 2025 Student Entrepreneurship Development Program (P2MW)',
                'excerpt_id' => 'Selamat kepada Tim Younme Telkom University yang berhasil lolos pendanaan Program Pembinaan Mahasiswa Wirausaha (P2MW) 2025!',
                'excerpt_en' => 'Congratulations to the Younme Team of Telkom University for passing the funding for the 2025 Student Entrepreneurship Development Program (P2MW)!',
                'body_id' => "Selamat kepada Tim Younme Telkom University yang berhasil lolos pendanaan Program Pembinaan Mahasiswa Wirausaha (P2MW) 2025! 🎉✨\n\nPencapaian ini menjadi bukti bahwa karya sederhana dapat berdampak besar, sekaligus inspirasi bahwa fashion bisa menjadi media perubahan sosial.\n\nTerus melangkah dan menginspirasi, Younme! 🚀💡",
                'body_en' => "Congratulations to the Younme Team of Telkom University for successfully securing funding from the 2025 Student Entrepreneurship Development Program (P2MW)! 🎉✨\n\nThis achievement stands as proof that simple work can make a big impact, while inspiring how fashion can be a medium for social change.\n\nKeep moving forward and inspiring, Younme! 🚀💡",
                'category' => 'prestasi',
                'featured_image' => '/images/news/achievement_P2MW.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(4)->addHours(4),
                'views' => 180,
            ],
            [
                'title_id' => 'Raihanul Hakim Raih Prestasi di Indonesian Science and Medical Olympiad 2025',
                'title_en' => 'Raihanul Hakim Achieves Award in the Indonesian Science and Medical Olympiad 2025',
                'excerpt_id' => 'Selamat kepada Raihanul Hakim atas prestasi gemilang yang diraih dalam Indonesian Science and Medical Olympiad 2025.',
                'excerpt_en' => 'Congratulations to Raihanul Hakim for the brilliant achievement in the Indonesian Science and Medical Olympiad 2025.',
                'body_id' => "Fakultas Rekayasa Industri mengucapkan selamat kepada Raihanul Hakim (FRI – S1 Teknik Logistik),\n\natas prestasi gemilang yang diraih dalam Indonesian Science and Medical Olympiad 2025 yang diselenggarakan oleh Braindicator Indonesia.",
                'body_en' => "Faculty of Industrial Engineering congratulates Raihanul Hakim (FRI - S1 Logistics Engineering),\n\nfor the outstanding achievement earned in the Indonesian Science and Medical Olympiad 2025 organized by Braindicator Indonesia.",
                'category' => 'prestasi',
                'featured_image' => '/images/news/achievement_medicalolympiad.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(4)->addHours(8),
                'views' => 150,
            ],
            [
                'title_id' => 'Ibu Leo Rama Kristiana Terpilih sebagai Penerima Program Hibah Konten Daring 2025',
                'title_en' => 'Leo Rama Kristiana Selected as Recipient of 2025 Online Content Grant Program',
                'excerpt_id' => 'Selamat kepada Ibu Leo Rama Kristiana, S.T., M.T. atas pencapaian sebagai Penerima Program Hibah Pengembangan Konten Pembelajaran Daring Tahun 2025.',
                'excerpt_en' => 'Congratulations to Mrs. Leo Rama Kristiana, S.T., M.T. on the achievement as a Recipient of the 2025 Online Learning Content Development Grant Program.',
                'body_id' => "Selamat kepada Ibu Leo Rama Kristiana, S.T., M.T. (Dosen S1 Digital Suply Chain/Teknik Logistik) atas pencapaian sebagai Penerima Program Hibah Pengembangan Konten Pembelajaran Daring Tahun 2025 Mata Kuliah Riset Operasi 2 dari Direktorat Pasca Sarjana dan Advanced Learning (PSAL), Telkom University.\n\nSemoga keberhasilan ini semakin menginspirasi dalam menghadirkan inovasi pembelajaran digital yang berkualitas.",
                'body_en' => "Congratulations to Mrs. Leo Rama Kristiana, S.T., M.T. (Lecturer in S1 Digital Supply Chain/Logistics Engineering) on the achievement as a Recipient of the 2025 Online Learning Content Development Grant Program for the Operations Research 2 course from the Directorate of Postgraduate and Advanced Learning (PSAL), Telkom University.\n\nMay this success inspire further innovations in quality digital learning.",
                'category' => 'prestasi',
                'featured_image' => '/images/news/achievement_programhibah.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(4)->addHours(12),
                'views' => 160,
            ],
            [
                'title_id' => 'Pendaftaran Seminar Hasil Tugas Akhir Prodi S1 Teknik Logistik (DSC)',
                'title_en' => 'Thesis Result Seminar Registration for S1 Logistics Engineering (DSC)',
                'excerpt_id' => 'Bagi Mahasiswa yang telah menyelesaikan Tugas Akhir silakan melakukan pendaftaran Seminar Hasil.',
                'excerpt_en' => 'For students who have completed their Final Thesis, please register for the Thesis Result Seminar.',
                'body_id' => "Bagi Mahasiswa yang sudah menyelesaikan Tugas Akhir dan Siap Sidang , silahkan untuk melakukan pendaftaran Seminar Hasil sesuai jadwal pada link berikut : https://s.id/PendaftaranSeminarHasilDSC",
                'body_en' => "For students who have completed their Final Thesis and are ready for defense, please register for the Result Seminar in accordance with the schedule at the following link: https://s.id/PendaftaranSeminarHasilDSC",
                'category' => 'pengumuman',
                'featured_image' => '/images/news/pengumuman_pendaftaranseminarhasil.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(5),
                'views' => 174,
            ],
            [
                'title_id' => 'Webinar Kenal Tel-U 2026: Bergabunglah Bersama Berbagai Program Studi FRI',
                'title_en' => 'Kenal Tel-U 2026 Webinar: Join Various Study Programs at FRI',
                'excerpt_id' => 'Jangan lewatkan kesempatan bergabung dengan webinar Kenal Tel-U bersama prodi impianmu.',
                'excerpt_en' => 'Do not miss the opportunity to join the Kenal Tel-U webinar with your dream study program.',
                'body_id' => "Kenal Tel-U hadir kembali bersama dengan berbagai Program Studi di Telkom University\n\nJangan lewatkan kesempatan bergabung dengan webinar Kenal Tel-U! 🙌\n\n📌 Kamis, 2 April 2026\n🕑 15.00 WIB - selesai\n\n🔖 https://smb.telkomuniversity.ac.id/daftar-kenal-tel-u\n\nAyo, ajak teman - teman lainnya supaya semakin rame dan seru! Sampai ketemu 🙋‍♀️",
                'body_en' => "Kenal Tel-U is back with various Study Programs at Telkom University\n\nDon't miss the opportunity to join the Kenal Tel-U webinar! 🙌\n\n📌 Thursday, April 2, 2026\n🕑 15.00 WIB - finish\n\n🔖 https://smb.telkomuniversity.ac.id/daftar-kenal-tel-u\n\nCome on, invite other friends to make it even more crowded and fun! See you there 🙋‍♀️",
                'category' => 'berita',
                'featured_image' => '/images/news/news_webinarkenaltelyu.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(6),
                'views' => 155,
            ],
            [
                'title_id' => 'Etika Berkirim Pesan pada Dosen bagi Mahasiswa',
                'title_en' => 'Messaging Ethics to Lecturers for University Students',
                'excerpt_id' => 'Pesan yang disampaikan dengan baik mencerminkan sikap hormat, kedewasaan, dan sikap profesional.',
                'excerpt_en' => 'A well-communicated message reflects respect, maturity, and a professional student attitude.',
                'body_id' => "Sudahkah kamu mengirim pesan ke dosen dengan etika yang tepat?\n\nBerkirim pesan kepada dosen bukan sekadar menyampaikan pertanyaan, tetapi juga mencerminkan sikap profesional dan kedewasaan kita sebagai mahasiswa.\nPesan yang disampaikan dengan baik akan mencerminkan sikap hormat, kedewasaan, dan kesiapan menjadi bagian komunitas akademik.\n\ncara kita berkomunikasi hari ini adalah latihan untuk dunia profesional nanti. 💼✨",
                'body_en' => "Have you sent a message to the lecturer with the right ethics?\n\nMessaging lecturers is not just about conveying questions, it also reflects our professional attitude and maturity as students.\nA well-communicated message reflects respect, maturity, and readiness to be part of the academic community.\n\nHow we communicate today is practice for the professional world tomorrow. 💼✨",
                'category' => 'berita',
                'featured_image' => '/images/news/news_etikaberkirimpesanpadadosen.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(7),
                'views' => 294,
            ],
            [
                'title_id' => 'Undangan Pertemuan Orang Tua/Wali Mahasiswa Fakultas Rekayasa Industri',
                'title_en' => 'Invitation to Parent/Guardian Meeting of Faculty of Industrial Engineering',
                'excerpt_id' => 'Pertemuan silaturahmi dekanat dan ketua prodi bersama orang tua/wali mahasiswa FRI.',
                'excerpt_en' => 'Gathering dekanat and head of study programs with parents/guardians of FRI students.',
                'body_id' => "[Undangan Pertemuan Orang Tua/Wali Mahasiswa Fakultas Rekayasa Industri]\n\nKepada Bapak/Ibu Yth.\nSehubungan dengan akan dimulainya perkuliahan Semester Genap Tahun Akademik 2025/2026, Dengan ini kami mengundang Bapak/Ibu untuk berkenan hadir dalam kegiatan *Pertemuan Orang Tua/Wali Mahasiswa bersama Fakultas Rekayasa Industri* yang akan dilaksanakan pada :\n\n🗓 Sabtu, 14 Februari 2026\n⏰ 08.00 WIB - selesai\n🎥Zoom Meeting\n\nAgenda :\n1. Silaturahmi Dekanat dan Ketua Program Studi dengan Orang Tua/Wali Mahasiswa\n2. Diskusi dan Penyampaian Informasi Akademik\n3. Lain-lain\n\nDemikian undangan ini kami sampaikan, atas perhatian dan kerja sama yang baik, kami ucapkan terima kasih",
                'body_en' => "[Invitation to Parent/Guardian Meeting of Faculty of Industrial Engineering]\n\nDear Parents/Guardians,\nIn connection with the commencement of the Even Semester of the 2025/2026 Academic Year, we hereby invite you to attend the *Parent/Guardian Meeting with the Faculty of Industrial Engineering* scheduled for:\n\n🗓 Saturday, February 14, 2026\n⏰ 08.00 WIB - finish\n🎥Zoom Meeting\n\nAgenda:\n1. Gathering of Dekanat and Head of Study Programs with Parents/Guardians\n2. Discussion and Presentation of Academic Information\n3. Others\n\nThank you for your attention and cooperation.",
                'category' => 'berita',
                'featured_image' => '/images/news/news_pertemuanorangtuawalimahasiswa.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(8),
                'views' => 110,
            ],
            [
                'title_id' => 'Expo Capstone Design FRI 2026: Ruang Ide dan Solusi Nyata',
                'title_en' => 'FRI Capstone Design Expo 2026: Space of Ideas and Real Solutions',
                'excerpt_id' => 'Ratusan karya Capstone Design Project ditampilkan untuk menjawab berbagai tantangan industri.',
                'excerpt_en' => 'Hundreds of student Capstone Design works exhibited to answer various industrial challenges.',
                'body_id' => "Expo Capstone Design FRI 2026 menjadi ruang bertemunya ide, proses belajar, dan solusi nyata.\nRatusan karya mahasiswa ditampilkan, didiskusikan, dan sebagian telah diimplementasikan untuk menjawab tantangan di berbagai sektor.\n\nLebih dari sekadar pameran, kegiatan ini membuka ruang berbagi gagasan, kolaborasi, dan pembelajaran bermakna bagi semua yang terlibat.\n\nTerima kasih kepada seluruh mahasiswa, dosen, dan pengunjung yang telah menjadi bagian dari perjalanan karya mahasiswa ini.",
                'body_en' => "FRI Capstone Design Expo 2026 serves as a meeting space for ideas, learning processes, and real solutions.\nHundreds of student works were exhibited, discussed, and some have been implemented to address challenges across various sectors.\n\nMore than just an exhibition, this event opens space for sharing concepts, collaboration, and meaningful learning for everyone involved.\n\nThank you to all students, lecturers, and visitors who participated in this student journey.",
                'category' => 'berita',
                'featured_image' => '/images/news/news_pamerankaryamahasiswa.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(9),
                'views' => 165,
            ],
            [
                'title_id' => 'Talkshow Expo Capstone Project FRI 2026: From Ideas to Impact',
                'title_en' => 'Talkshow Expo Capstone Project FRI 2026: From Ideas to Impact',
                'excerpt_id' => 'Temukan strategi membangun inovasi berbasis teknologi dalam talkshow bersama praktisi industri.',
                'excerpt_en' => 'Discover strategies for building tech-based innovations in this talkshow with industry experts.',
                'body_id' => "Talkshow Expo Capstone Project FRI 2026\nFrom Ideas to Impact: Students as Future Technopreneurs\n\nBagaimana ide mahasiswa dapat berkembang menjadi solusi dan peluang nyata? Temukan jawabannya dalam talkshow bersama para praktisi industri yang akan berbagi pengalaman, insight, dan strategi membangun inovasi berbasis teknologi.\n\n📅 Kamis, 15 Januari 2026\n⏰ 12.15 – 14.30 WIB\n📍 Lt. 2 Gedung TULT\n\nJangan lewatkan kesempatan untuk belajar langsung dari para profesional dan memperluas wawasan tentang dunia technopreneurship.",
                'body_en' => "Talkshow Expo Capstone Project FRI 2026\nFrom Ideas to Impact: Students as Future Technopreneurs\n\nHow can student ideas evolve into real solutions and opportunities? Find the answer in this talkshow with industry practitioners sharing experiences, insights, and strategies to build tech-based innovation.\n\n📅 Thursday, January 15, 2026\n⏰ 12.15 – 14.30 WIB\n📍 2nd Floor, TULT Building\n\nDo not miss this opportunity to learn directly from professionals and widen your horizon about technopreneurship.",
                'category' => 'berita',
                'featured_image' => '/images/news/news_talkshow.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(10),
                'views' => 203,
            ],
            [
                'title_id' => 'Exhibition & Talkshow Capstone Design Project S1 Digital Supply Chain',
                'title_en' => 'Exhibition & Talkshow Capstone Design Project S1 Digital Supply Chain',
                'excerpt_id' => 'Pameran Capstone Design Project Mahasiswa Angkatan 2022 S1 Digital Supply Chain.',
                'excerpt_en' => 'Exhibition of Capstone Design Projects by Batch 2022 Digital Supply Chain Students.',
                'body_id' => "✨ EXHIBITION & TALKSHOW CAPSTONE DESIGN PROJECT ✨\n\nSaatnya melihat karya terbaik mahasiswa Program Studi S1 Digital Supply Chain dalam Pameran Capstone Design Project yang mengusung tema “From Ideas to Impact: Students as Future Technopreneurs”,\n\n🗓 Selasa – Kamis, 13–15 Januari 2026\n⏰ 08.00 WIB – selesai\n📍 Lantai 2 Gedung TULT\n\n👩‍🎓 Peserta Pameran:\nMahasiswa Angkatan 2022 (TL-46)\n\n📌 Catatan:\nWajib dihadiri oleh Mahasiswa Angkatan 2023 (TL-47) sebagai syarat mengambil Mata Kuliah dan memilih kelompok Capstone.\n\nYuk, datang dan saksikan ide-ide hebat yang siap memberi dampak nyata! 🚀",
                'body_en' => "✨ EXHIBITION & TALKSHOW CAPSTONE DESIGN PROJECT ✨\n\nIt is time to see the best works of S1 Digital Supply Chain students in the Capstone Design Project Exhibition themed “From Ideas to Impact: Students as Future Technopreneurs”.\n\n🗓 Tuesday – Thursday, January 13–15, 2026\n⏰ 08.00 WIB – finish\n📍 2nd Floor, TULT Building\n\n👩‍🎓 Exhibition Participants:\nBatch 2022 Students (TL-46)\n\n📌 Note:\nMandatory attendance for Batch 2023 Students (TL-47) as a prerequisite to enroll in the Capstone Course.\n\nCome and witness great ideas ready to make a real impact! 🚀",
                'category' => 'berita',
                'featured_image' => '/images/news/news_talkshowcapstone.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(11),
                'views' => 177,
            ],
            [
                'title_id' => 'Pendaftaran Seminar Hasil Tugas Akhir Semester Genap',
                'title_en' => 'Even Semester Thesis Result Seminar Registration',
                'excerpt_id' => 'Pengumuman alur pendaftaran Seminar Hasil DSC bagi mahasiswa S1 Teknik Logistik.',
                'excerpt_en' => 'Announcement of the Thesis Result Seminar registration steps for S1 Logistics Engineering students.',
                'body_id' => "Bagi Mahasiswa yang sudah menyelesaikan Tugas Akhir dan Siap Sidang* , silahkan untuk melakukan pendaftaran Seminar Hasil sesuai jadwal pada link berikut : https://s.id/PendaftaranSeminarHasilDSC",
                'body_en' => "For students who have completed their Final Thesis and are ready for defense*, please register for the Result Seminar in accordance with the schedule at the following link: https://s.id/PendaftaranSeminarHasilDSC",
                'category' => 'pengumuman',
                'featured_image' => '/images/news/pengumuman_pendaftaransemhas.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(12),
                'views' => 84,
            ],
            [
                'title_id' => 'ILOCOS: Kompetisi Analisis Kasus Rantai Pasok Digital',
                'title_en' => 'ILOCOS: Digital Supply Chain Case Analysis Competition',
                'excerpt_id' => 'Ajang kompetisi dan diskusi kasus logistik riil bersama praktisi industri di ILOCOS.',
                'excerpt_en' => 'Case competition and discussion platform on real logistics with industry practitioners at ILOCOS.',
                'body_id' => "ILOCOS menjadi wadah bagi peserta untuk mengasah kemampuan analisis dan pemecahan masalah pada kasus nyata logistik dan supply chain, sekaligus memperoleh wawasan langsung mengenai tren digital supply chain bersama praktisi industri.",
                'body_en' => "ILOCOS serves as a platform for participants to sharpen their analysis and problem-solving skills on real logistics and supply chain cases, while gaining direct insights into digital supply chain trends alongside industry practitioners.",
                'category' => 'berita',
                'featured_image' => '/images/news/news_ilocos.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(13),
                'views' => 156,
            ],
            [
                'title_id' => 'Kunjungan Industri S1 Teknik Logistik ke PT Kayaba Indonesia',
                'title_en' => 'S1 Logistics Engineering Industrial Visit to PT Kayaba Indonesia',
                'excerpt_id' => 'Mahasiswa S1 Teknik Logistik mengobservasi proses manufaktur otomotif secara langsung.',
                'excerpt_en' => 'S1 Logistics Engineering students observe automotive manufacturing processes first-hand.',
                'body_id' => "Kunjungan ini bukan hanya memperlihatkan proses manufaktur otomotif, tetapi juga membuka mata mahasiswa tentang tuntutan kompetensi di dunia kerja. Pengalaman nyata di industri menjadi motivasi untuk terus mengasah kemampuan teknis dan profesional.",
                'body_en' => "This visit not only showed the automotive manufacturing process, but also opened students' eyes to competency requirements in the professional world. Real experience in the industry motivates students to keep sharpening technical and professional skills.",
                'category' => 'berita',
                'featured_image' => '/images/news/kunjungan_kayabaindonesia.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(14),
                'views' => 198,
            ],
            [
                'title_id' => 'Guest Lecture: Lean Supply Chain Case in Palm Oil Industry',
                'title_en' => 'Guest Lecture: Lean Supply Chain Case in Palm Oil Industry',
                'excerpt_id' => 'Kuliah tamu wajib bagi angkatan 2022 menghadirkan pembicara ahli dari Malaysia.',
                'excerpt_en' => 'Mandatory guest lecture for the 2022 batch featuring an expert speaker from Malaysia.',
                'body_id' => "📣 Guest Lecture Alert!\n\nYuk ikuti kuliah tamu bertema:\n“Lean Supply Chain: Case in Palm Oil Industry” 🌿🏭\n\nAcara ini akan menghadirkan seorang akademisi dari universitas teknik terkemuka di Malaysia untuk berbagi wawasan tentang penerapan lean supply chain di industri kelapa sawit.\n\n📅 Senin, 8 Desember 2025\n🏢 Auditorium Gedung TULT, Lantai 16.\n\nAcara ini wajib untuk mahasiswa Program Studi S1 Digital Supply Chain angkatan 2022 (DSC-46) sebagai pengganti kelas mata kuliah pilihan.\n\nJangan lewatkan kesempatan untuk belajar langsung dari para ahli! 🎓✨",
                'body_en' => "📣 Guest Lecture Alert!\n\nJoin our guest lecture themed:\n\"Lean Supply Chain: Case in Palm Oil Industry\" 🌿🏭\n\nThis event will feature an academician from a leading technical university in Malaysia to share insights about lean supply chain applications in the palm oil industry.\n\n📅 Monday, December 8, 2025\n🏢 Auditorium TULT Building, 16th Floor.\n\nThis event is mandatory for Batch 2022 (DSC-46) S1 Digital Supply Chain students as a replacement for elective classes.\n\nDon't miss the chance to learn directly from the experts! 🎓✨",
                'category' => 'berita',
                'featured_image' => '/images/news/news_talkshowpalmoil.png',
                'is_featured' => false,
                'status' => 'published',
                'published_at' => now()->subDays(15),
                'views' => 220,
            ]
        ];

        foreach ($newsData as $item) {
            News::create([
                'title_id' => $item['title_id'],
                'title_en' => $item['title_en'],
                'slug' => Str::slug($item['title_id']),
                'excerpt_id' => $item['excerpt_id'],
                'excerpt_en' => $item['excerpt_en'],
                'body_id' => $item['body_id'],
                'body_en' => $item['body_en'],
                'category' => $item['category'],
                'featured_image' => $item['featured_image'],
                'status' => $item['status'],
                'is_featured' => $item['is_featured'],
                'published_at' => $item['published_at'],
                'views' => $item['views'],
            ]);
        }
    }
}
